name: Surveillance logements CROUS Evry

on:
  workflow_dispatch:

  schedule:
    - cron: "*/1 * * * *"

jobs:
  surveillance:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer les fichiers du dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Vérifier les logements CROUS
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
